# Generated by Django 6.0.4 on 2026-04-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=120)),
                ('tagline', models.CharField(default='Find me across the web', max_length=180)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site profile',
                'verbose_name_plural': 'Site profile',
            },
        ),
    ]
