# Generated by Django 6.0.4 on 2026-04-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_siteprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='tab',
            field=models.CharField(default='Main', max_length=60),
        ),
    ]
