# Generated by Django 6.0.4 on 2026-04-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_link_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
