# Generated by Django 6.0.4 on 2026-04-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_link_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='heart_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
