# Generated by Django 6.0.4 on 2026-04-16 00:00

from django.db import migrations, models


def clear_legacy_defaults(apps, schema_editor):
    SiteProfile = apps.get_model('links', 'SiteProfile')
    SiteProfile.objects.filter(name='Your Name').update(name='')
    SiteProfile.objects.filter(tagline='Find me across the web').update(tagline='')


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_siteprofile_heart_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.RunPython(clear_legacy_defaults, migrations.RunPython.noop),
    ]
